### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by edjustice** [SkaMessi10/Hackoff_Data_BitsPlease#1]
Hi so I wanted to know how could you started working on the hackathon even before it has started. shoudnt we make it during the hack

**Comment by ArnavNair** [comment]
Hey! So what you're saying is indeed the general trend that Hackathons follow. However, some of them, such as this one, release a list of possible ideas to work on beforehand, and allow participants to prepare to a certain degree before the event. Hope this clears your confusion.

**Comment by ArnavNair** [comment]
Hey @edjustice ! What you've said is indeed the general trend followed by many Hackathons. However, some such as this one release a list of general ideas beforehand and allow participating teams to prepare to a certain extent before the event. Hope this clears your confusion.

**Comment by edjustice** [comment]
@ArnavNair Thankyou, I didnt know that.

**Comment by ArnavNair** [comment]
No problem!
